// Builds seed/seed.sql from seed/program.json (SPEC §6). Idempotent: safe to run on every deploy.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const here = (p) => fileURLToPath(new URL(p, import.meta.url));
const data = JSON.parse(readFileSync(here("./program.json"), "utf8"));
const CREATED = "2026-09-27T00:00:00.000Z";

const q = (v) => (v === null || v === undefined ? "NULL" : typeof v === "number" ? String(v) : `'${String(v).replace(/'/g, "''")}'`);
const out = ["-- Generated by seed/generate.mjs from seed/program.json. Do not edit by hand."];

for (const [k, v] of Object.entries(data.settings)) {
  out.push(`INSERT OR IGNORE INTO settings (key, value) VALUES (${q(k)}, ${q(v)});`);
}
for (const e of data.exercises) {
  out.push(
    `INSERT INTO exercises (id, name_fa, name_en, muscle_primary, is_lower, equipment, cue_fa) VALUES (${[e.id, e.name_fa, e.name_en, e.muscle_primary, e.is_lower, e.equipment, e.cue_fa].map(q).join(", ")})` +
      ` ON CONFLICT (id) DO UPDATE SET name_fa = excluded.name_fa, name_en = excluded.name_en, muscle_primary = excluded.muscle_primary, is_lower = excluded.is_lower, equipment = excluded.equipment, cue_fa = excluded.cue_fa;`
  );
}
for (const p of data.programs) {
  out.push(
    `INSERT INTO programs (id, name, active, created_at) VALUES (${[p.id, p.name, p.active, CREATED].map(q).join(", ")})` +
      ` ON CONFLICT (id) DO UPDATE SET name = excluded.name, active = excluded.active;`
  );
  p.days.forEach((d, di) => {
    out.push(
      `INSERT INTO program_days (id, program_id, position, name_fa, name_en, focus_fa, est_minutes) VALUES (${[d.id, p.id, di + 1, d.name_fa, d.name_en, d.focus_fa, d.est_minutes].map(q).join(", ")})` +
        ` ON CONFLICT (id) DO UPDATE SET program_id = excluded.program_id, position = excluded.position, name_fa = excluded.name_fa, name_en = excluded.name_en, focus_fa = excluded.focus_fa, est_minutes = excluded.est_minutes;`
    );
    out.push(`DELETE FROM day_exercises WHERE day_id = ${q(d.id)};`);
    d.ex.forEach((x, xi) => {
      const row = [`${d.id}_${xi + 1}`, d.id, x.x, xi + 1, x.sets, x.reps[0], x.reps[1], x.per_leg ?? 0, x.time ?? 0, x.rest, x.tag ?? null, x.main ?? 0];
      out.push(`INSERT INTO day_exercises (id, day_id, exercise_id, position, sets, reps_min, reps_max, per_leg, is_time, rest_sec, superset_tag, is_main) VALUES (${row.map(q).join(", ")});`);
    });
  });
}

const sql = out.join("\n") + "\n";
if (process.argv.includes("--check")) {
  const current = readFileSync(here("./seed.sql"), "utf8");
  if (current !== sql) {
    console.error("seed/seed.sql is out of date; run `npm run seed:build`.");
    process.exit(1);
  }
} else {
  writeFileSync(here("./seed.sql"), sql);
  console.log(`seed/seed.sql: ${out.length - 1} statements`);
}
